apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo-development
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: development
  url: https://github.com/pg2000/flux-demo
  timeout: 30s
